# Generated by Django 5.2.7 on 2025-10-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yip_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customermodel',
            new_name='AdminModel',
        ),
    ]
