# Generated by Django 5.2.7 on 2025-10-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yip_form', '0002_rename_customermodel_adminmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodel',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yipform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
