# Generated by Django 5.2.7 on 2025-10-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yip_form', '0003_adminmodel_password_yipform_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yipform',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
