# Generated by Django 5.2.7 on 2025-10-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yip_form', '0004_yipform_razorpay_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminModel',
            new_name='CustomerModel',
        ),
    ]
