# Generated by Django 5.2.7 on 2025-10-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yip_form', '0005_rename_adminmodel_customermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerModel',
            new_name='AdminModel',
        ),
    ]
